robot:
  type: so101_follower
  port: /dev/ttyACM0
  id: my_awesome_follower_arm
  calibration_dir: null   # 필요하면 "/home/..../calibration/robots/so101_follower" 같은 경로로

cameras:
  width: 640
  height: 480
  fps: 30
  fourcc: MJPG
  indices:
    right: 2
    left: 6
    global: 4
    wrist: 0

runtime:
  fps: 30
  duration_s_default: 10
  device: auto     # auto|cpu|cuda
  use_amp: true

policies:
  policy1:
    repo_id: ispaik06/act_panbot_task2_3
    task: null
    rename_map: {}
    dataset_repo_id: null

  policy2:
    repo_id: ispaik06/act_panbot_task3_3
    task: null
    rename_map: {}
    dataset_repo_id: null
